"""Project-wide configuration defaults."""

from pathlib import Path

APP_TITLE = "Neural Style Transfer App"
APP_ORGANIZATION = "Course Project"
APP_WINDOW_WIDTH = 1280
APP_WINDOW_HEIGHT = 800
APP_MINIMUM_WIDTH = 1180
APP_MINIMUM_HEIGHT = 760

DEFAULT_IMAGE_SIZE = 768
DEFAULT_NUM_STEPS = 300
DEFAULT_STYLE_STRENGTH = 1.0
MIN_NUM_STEPS = 50
MAX_NUM_STEPS = 1000
MIN_STYLE_STRENGTH = 0.1
MAX_STYLE_STRENGTH = 10.0
GUI_MIN_IMAGE_SIZE = 256
GUI_MAX_IMAGE_SIZE = 1536

GUI_IMAGE_FILE_FILTER = "Images (*.png *.jpg *.jpeg *.bmp *.webp)"
GUI_PREVIEW_WIDTH = 320
GUI_PREVIEW_HEIGHT = 220

DEFAULT_OUTPUT_DIR = Path("outputs")
DEFAULT_OUTPUT_STEM = "result"
DEFAULT_METADATA_SUFFIX = ".json"

SUPPORTED_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".bmp", ".webp"}
