"""Project-wide configuration defaults."""

from pathlib import Path

APP_TITLE = "风格迁移工作台"
APP_ORGANIZATION = "计算机视觉课程项目"
APP_WINDOW_WIDTH = 1280
APP_WINDOW_HEIGHT = 800
APP_MINIMUM_WIDTH = 1180
APP_MINIMUM_HEIGHT = 760

DEFAULT_IMAGE_SIZE = 768
DEFAULT_NUM_STEPS = 300
DEFAULT_STYLE_STRENGTH = 1.0
DEFAULT_CONTENT_BLEND = 0.25
DEFAULT_TV_WEIGHT = 0.0
DEFAULT_HISTOGRAM_WEIGHT = 0.0
DEFAULT_INIT_MODE = "content"
MIN_NUM_STEPS = 50
MAX_NUM_STEPS = 1000
MIN_STYLE_STRENGTH = 0.1
MAX_STYLE_STRENGTH = 10.0
MIN_CONTENT_BLEND = 0.0
MAX_CONTENT_BLEND = 1.0
MIN_TV_WEIGHT = 0.0
GUI_MIN_IMAGE_SIZE = 256
GUI_MAX_IMAGE_SIZE = 1536

INIT_MODE_CHOICES = ("content", "content_noise", "noise")

ENHANCED_MODE_NUM_STEPS = 800
ENHANCED_MODE_STYLE_STRENGTH = 2.5
ENHANCED_MODE_CONTENT_BLEND = 0.0
ENHANCED_MODE_TV_WEIGHT = 1e-4
ENHANCED_MODE_INIT_MODE = "content_noise"

PAPER_MODE_NUM_STEPS = 1000
PAPER_MODE_STYLE_STRENGTH = 1.0
PAPER_MODE_CONTENT_BLEND = 0.0
PAPER_MODE_TV_WEIGHT = 1e-4
PAPER_MODE_HISTOGRAM_WEIGHT = 1.0
PAPER_MODE_INIT_MODE = "noise"

GUI_IMAGE_FILE_FILTER = "Images (*.png *.jpg *.jpeg *.bmp *.webp)"
GUI_PREVIEW_WIDTH = 320
GUI_PREVIEW_HEIGHT = 220

DEFAULT_OUTPUT_DIR = Path("outputs")
DEFAULT_OUTPUT_STEM = "result"
DEFAULT_METADATA_SUFFIX = ".json"

SUPPORTED_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".bmp", ".webp"}
